config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/home', to: 'home#index'
  #DEVISE
  devise_for :users, controllers: { sessions: 'sessions' }, skip: :registrations
  devise_for :clients, :lawyers, :paralegals, skip: :sessions, controllers: { registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  #LOCATIONS
  resources :locations, only: :create

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

class Client < User
  belongs_to :location
  accepts_nested_attributes_for :location, reject_if: :all_blank

  def location_attributes=(location_attributes)
    location = Location.where(location_type: 0)
    self.location = location.find_or_create_by(location_attributes)
  end
end

app/models/lawyer.rb
# frozen_string_literal: true

class Lawyer < User
  belongs_to :location
  accepts_nested_attributes_for :location, reject_if: :all_blank
  has_and_belongs_to_many :paralegals,
                          class_name: 'Paralegal',
                          join_table: :lawyers_paralegals,
                          foreign_key: :lawyer_id

  def location_attributes=(location_attributes)
    location_attributes[:location_type] = 1
    postal = location_attributes[:postal]
    authentication = location_attributes[:authentication]

    self.location =
      if [authentication, postal].all?(&:present?)
        Location.find_by(postal: postal, authentication: authentication)
      else
        Location.create(location_attributes)
      end
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  enum location_type: %i[home office]

  geocoded_by :postal
  after_validation :geocode, if: :postal_change

  has_many :clients
  has_many :lawyers
  has_many :paralegals

  validates :postal, :adress, presence: true
  validates :name, presence: true, if: :office?, on: :create

  before_validation do
    self[:city] = Geocoder.search("DE, #{postal}").map(&:city).join
    self[:authentication] = SecureRandom.hex(4) if office?
  end
end

app/models/paralegal.rb
# frozen_string_literal: true

class Paralegal < User
  belongs_to :location
  accepts_nested_attributes_for :location, reject_if: :all_blank
  has_and_belongs_to_many :lawyers,
                          class_name: 'Lawyer',
                          join_table: :lawyers_paralegals,
                          foreign_key: :paralegal_id

  def location_attributes=(location_attributes)
    locations = Location.where(location_type: 1)
    self.location = locations.find_by(location_attributes)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum status: %i[active inactive]
  GENDER = %w[male female].freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :first_name, :last_name, :birthday, :gender, presence: true
  validates :gender, inclusion: { in: GENDER }

  before_save do
    first_name.capitalize!
    last_name.capitalize!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  devise_group :user, contains: %i[client lawyer paralegal]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [
      :email, :password, :password_confirmation, :remember_me,
      :first_name, :last_name, :birthday, :gender, :type, :location_id,
      { location_attributes: %i[postal authentication name adress] }
    ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  private

  def locations_params
    params.fetch(:location, {}).permit(:location_type, :city, :adress, :name, :authentication, :latitude, :longitude)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    home_path
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
  def create
    rtn = super
    sign_in(resource.type.underscore, resource.type.constantize.send(:find, resource.id)) unless resource.type.nil?
    rtn
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_type(user)
    user.type.parameterize
  end

  def postal
    request.env['ipinfo'].postal
  end

  def city
    request.env['ipinfo'].city
  end
end

app/views/home/index.html.erb
<%= render 'layouts/sidebar'%>

app/views/layouts/_footer.html.erb
<div class="footer-basic mt-auto">
  <footer class="page-footer">
    <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Services</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
    <p class="copyright">Jufa ©<%= Time.zone.today.year%></p>
  </footer>
</div>

app/views/layouts/_form.html.erb
<div class="wrapper">
  <div class="formContent">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { autocomplete: "off" }) do |f| %>
      <%= render "shared/error_messages", resource: resource %>
        <%= f.email_field :email, autofocus: true, placeholder: "email" %>
        <%= f.text_field :first_name, autofocus: true, placeholder: "first name" %>
        <%= f.text_field :last_name, autofocus: true, placeholder: "last name" %><br />
        <div class="container">
          <div class="funkyradio row justify-content-md-center">
            <div class="funkyradio-male col-5">
              <%= f.radio_button :gender, 'male' %>
              <%= f.label :gender_male, "Male" %>
            </div>
            <div class="funkyradio-female col-5">
              <%= f.radio_button :gender, 'female' %>
              <%= f.label :gender_female, "Female" %>
            </div>
          </div>
        </div>
        <%= f.text_field :birthday, placeholder: 'birthday: dd/mm/yyyy', class: 'flatpickr' %>
        <%= f.password_field :password, placeholder: "password" %>
        <%= f.password_field :password_confirmation, placeholder: "repeat password" %>
      <%= yield f if block_given?%>
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Jufa", home_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
    <ul class="nav pull-right">
      <% if user_signed_in?%>
        <%= link_to "My Profile", edit_registration_path(current_user.type.downcase), class: "nav-link" %>
      <% end %>
      <% unless user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sign Up
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Client", new_registration_path(:client), class: "dropdown-item" %>
            <%= link_to "Lawyer", new_registration_path(:lawyer), class: "dropdown-item" %>
            <%= link_to "Paralegal", new_registration_path(:paralegal), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_session_path(current_user), method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
    <li class="active">
      <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-dashboard fa-stack-1x "></i></span> Dashboard</a>
      <ul class="nav-pills nav-stacked" style="list-style-type:none;">
        <li><a href="#">link1</a></li>
        <li><a href="#">link2</a></li>
      </ul>
    </li>
    <li>
      <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Shortcut</a>
      <ul class="nav-pills nav-stacked" style="list-style-type:none;">
        <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>link1</a></li>
        <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>link2</a></li>
      </ul>
    </li>
    <li>
      <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-cloud-download fa-stack-1x "></i></span>Overview</a>
    </li>
    <li>
      <a href="#"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-cart-plus fa-stack-1x "></i></span>Events</a>
    </li>
    <li>
      <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-youtube-play fa-stack-1x "></i></span>About</a>
    </li>
    <li>
      <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-wrench fa-stack-1x "></i></span>Services</a>
    </li>
    <li>
      <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>Contact</a>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jufa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container-fluid" style="min-height:800px;">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/edit/_personal_data.erb
<div class="wrapper">
  <div class="formContent">
    <h2>Personal Data</h2>

    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= render "shared/error_messages", resource: resource %>
        <%= f.email_field :email, autofocus: true, placeholder: "email", disabled: true %>
        <%= f.text_field :first_name, autofocus: true, placeholder: "first name" %>
        <%= f.text_field :last_name, autofocus: true, placeholder: "last name" %><br />
      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
      <% end %>

        <%= f.password_field :password, placeholder: "New Password" %>

      <div class="field">
        <%= f.password_field :password_confirmation, placeholder: "Repeat" %>
      </div>

      <div class="field">
        <%= f.password_field :current_password, autocomplete: "current-password", placeholder: "Current Password to confirm changes" %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>

    <h3>Cancel my account</h3>

    <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
  </div>
</div>